### ISSUE TITLE
Physical flow create fails on MariaDB

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#1004]
Fails when trying to insert logical flow

**Comment by davidwatkins73** [comment]
Could you provide a stack trace pls ?

**Comment by rovats** [comment]
```
Field 'id' doesn't have a default value / org.jooq.exception.DataAccessException
org.jooq.exception.DataAccessException: SQL [insert into `logical_flow` (
  `source_entity_kind`, 
  `source_entity_id`, 
  `target_entity_kind`, 
  `target_entity_id`, 
  `provenance`
)
values (
  ?, 
  ?, 
  ?, 
  ?, 
  ?
)]; Field 'id' doesn't have a default value
	at org.jooq.impl.Tools.translate(Tools.java:1690)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:659)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:177)
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:143)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:139)
	at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:185)
	at org.jooq.impl.UpdatableRecordImpl.access$000(UpdatableRecordImpl.java:85)
	at org.jooq.impl.UpdatableRecordImpl$1.operate(UpdatableRecordImpl.java:135)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:131)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:123)
	at com.khartec.waltz.data.logical_flow.LogicalFlowDao.addFlow(LogicalFlowDao.java:111)
	at com.khartec.waltz.service.logical_flow.LogicalFlowService.addFlow(LogicalFlowService.java:115)
	at com.khartec.waltz.service.physical_flow.PhysicalFlowService.ensureLogicalDataFlow(PhysicalFlowService.java:212)
	at com.khartec.waltz.service.physical_flow.PhysicalFlowService.create(PhysicalFlowService.java:151)
	at com.khartec.waltz.web.endpoints.api.PhysicalFlowEndpoint.createFlow(PhysicalFlowEndpoint.java:100)
```

**Comment by kamransaleem** [comment]
should be fixed as part of #946

**Comment by davidwatkins73** [comment]
@rovats - could you confirm pls ?

**Comment by rovats** [comment]
Still failing.. same error..
