### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1100]
Build failing. Test still use raw D3

**Comment by davidwatkins73** [comment]
```
calculateGroupSummary should calculate a summary by transposing and counting:
     ReferenceError: d3 is not defined
      at Object.calculateGroupSummary (client/ratings/directives/common.js:83:24)
      at Context.<anonymous> (test/ratings/test_calculateGroupSummary.js:15:9)
  2) calculateGroupSummary should give empty array for empty input array:
     ReferenceError: d3 is not defined
      at Object.calculateGroupSummary (client/ratings/directives/common.js:83:24)
      at Context.<anonymous> (test/ratings/test_calculateGroupSummary.js:15:9)
  3) calculateGroupSummary should give empty array for null input:
     ReferenceError: d3 is not defined
      at Object.calculateGroupSummary (client/ratings/directives/common.js:83:24)
      at Context.<anonymous> (test/ratings/test_calculateGroupSummary.js:15:9)
```
