### ISSUE TITLE
can't run from within unexploded war

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#117]
error:

````
16:10:36.247 [localhost-startStop-1] DEBUG c.k.w.w.e.a.StaticResourcesEndpoint - Registering static resources for mode DEPLOY
16:10:36.368 [localhost-startStop-1] ERROR spark.servlet.SparkFilter - Error when creating StaticResourceHandler
java.io.FileNotFoundException: class path resource [static] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/opt/dap/domains/tc0562/int1/tomcat/webapps/waltz-mssql.war!/WEB-INF/classes/static/
	at spark.utils.ResourceUtils.getFile(ResourceUtils.java:213) ~[spark-core-2.2.jar:na]
	at spark.resource.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:46) ~[spark-core-2.2.jar:na]
	at spark.servlet.SparkFilter.configureStaticResources(SparkFilter.java:144) [spark-core-2.2.jar:na]
	at spark.SparkBase.staticFileLocation(SparkBase.java:214) [spark-core-2.2.jar:na]
	at com.khartec.waltz.web.endpoints.api.StaticResourcesEndpoint.register(StaticResourcesEndpoint.java:49) [waltz-mssql.war:na]
	at com.khartec.waltz.web.Main.start(Main.java:82) [waltz-mssql.war:na]
	at com.khartec.waltz.web.WaltzApplication.init(WaltzApplication.java:26) [waltz-mssql.war:na]
	at spark.servlet.SparkFilter.init(SparkFilter.java:71) [spark-core-2.2.jar:na]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279) [catalina.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260) [catalina.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105) [catalina.jar:8.0.23]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4574) [catalina.jar:8.0.23]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5193) [catalina.jar:8.0.23]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.23]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.23]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.23]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.23]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945) [catalina.jar:8.0.23]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768) [catalina.jar:8.0.23]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_71]
````

**Comment by davidwatkins73** [comment]
Fixed as part of #105, see changes to StaticResourcesEndpoint.
