### ISSUE TITLE
Physical flow create fails if logical flow doesn't already exist

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#1513]
Attestation logic needs to be moved after the `logicalFlow == null` check

    java.lang.NullPointerException: null
	at com.khartec.waltz.service.physical_flow.PhysicalFlowService.ensureLogicalDataFlow(PhysicalFlowService.java:265)
	at com.khartec.waltz.service.physical_flow.PhysicalFlowService.create(PhysicalFlowService.java:191)
	at com.khartec.waltz.web.endpoints.api.PhysicalFlowEndpoint.createFlow(PhysicalFlowEndpoint.java:146)

**Comment by davidwatkins73** [comment]
@kamransaleem

**Comment by kamransaleem** [comment]
fixed as part of #1482
