### ISSUE TITLE
SurveyInstance: won't load

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1560]
```
java.lang.NumberFormatException: For input string: "undefined"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at com.khartec.waltz.web.WebUtilities.getLong(WebUtilities.java:123)
	at com.khartec.waltz.web.WebUtilities.getId(WebUtilities.java:128)
	at com.khartec.waltz.web.endpoints.api.SurveyInstanceEndpoint.lambda$register$182(SurveyInstanceEndpoint.java:41)
	at com.khartec.waltz.web.endpoints.EndpointUtilities.lambda$wrapDatumHandler$4(EndpointUtilities.java:99)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:127)
````

**Comment by davidwatkins73** [comment]
Stuggling to reproduce.
