### ISSUE TITLE
App view errors when fetching logical flows

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#1580]
Missing required attribute: `lastUpdatedBy`

```
java.lang.IllegalStateException: Cannot build LogicalFlow, some of required attributes are not set [lastUpdatedBy]
	at com.khartec.waltz.model.logical_flow.ImmutableLogicalFlow$Builder.build(ImmutableLogicalFlow.java:594)
	at com.khartec.waltz.data.logical_flow.LogicalFlowDao.lambda$static$0(LogicalFlowDao.java:62)
	at org.jooq.impl.ResultImpl.map(ResultImpl.java:2124)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:1258)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3467)
	at com.khartec.waltz.data.logical_flow.LogicalFlowDao.findByEntityReference(LogicalFlowDao.java:91)
	at com.khartec.waltz.service.logical_flow.LogicalFlowService.findByEntityReference(LogicalFlowService.java:106)
```

**Comment by davidwatkins73** [comment]
Think this may have been fixed with ddl update.  you'll need to remove a changeset and re-add

```
-- remove changelog
delete from DATABASECHANGELOG where id='20170214-1480-1';

-- revert db changes
ALTER TABLE waltz.logical_flow DROP last_updated_at;
ALTER TABLE waltz.logical_flow DROP last_updated_by;
```

**Comment by rovats** [comment]
Re-running the DDL fixes the issue..

**Comment by davidwatkins73** [comment]
thanks
