### ISSUE TITLE
Cannot add applications to lineage when no logical flow exists

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1759]

**Comment by kamransaleem** [comment]
10:35:04.497 [http-nio-11462-exec-8] ERROR com.khartec.waltz.web.Main - Exception: null / java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.khartec.waltz.service.attestation.AttestationService.attestPhysicalFlow(AttestationService.java:98)
	at com.khartec.waltz.service.physical_flow_lineage.PhysicalFlowLineageService.addContribution(PhysicalFlowLineageService.java:95)
	at com.khartec.waltz.web.endpoints.api.PhysicalFlowLineageEndpoint.addContribution(PhysicalFlowLineageEndpoint.java:165)
	at com.khartec.waltz.web.endpoints.EndpointUtilities.lambda$wrapDatumHandler$4(EndpointUtilities.java:97)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:127)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.java:192)
	at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:318)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
