### ISSUE TITLE
Investigate memory exhaustion when building trees

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#2177]

**Comment by davidwatkins73** [comment]
```
5:52:24.291 [qtp413885950-21] WARN  org.eclipse.jetty.server.HttpChannel - /api/entity-hierarchy/build/ORG_UNIT
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at com.khartec.waltz.common.hierarchy.HierarchyUtilities.parents(HierarchyUtilities.java:113)
	at com.khartec.waltz.service.entity_hierarchy.EntityHierarchyService.streamAncestors(EntityHierarchyService.java:206)
	at com.khartec.waltz.service.entity_hierarchy.EntityHierarchyService.lambda$streamItemsForNode$20(EntityHierarchyService.java:190)
	at com.khartec.waltz.service.entity_hierarchy.EntityHierarchyService$$Lambda$472/1564334450.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.khartec.waltz.service.entity_hierarchy.EntityHierarchyService.convertFlatNodesToHierarchyItems(EntityHierarchyService.java:184)
	at com.khartec.waltz.service.entity_hierarchy.EntityHierarchyService.buildFor(EntityHierarchyService.java:154)
	at com.khartec.waltz.service.entity_hierarchy.EntityHierarchyService.buildFor(EntityHierarchyService.java:147)
	at com.khartec.waltz.web.endpoints.api.EntityHierarchyEndpoint.buildByKindRoute(EntityHierarchyEndpoint.java:83)
	at com.khartec.waltz.web.endpoints.api.EntityHierarchyEndpoint$$Lambda$244/1565614310.apply(Unknown Source)
	at com.khartec.waltz.web.endpoints.EndpointUtilities.lambda$wrapDatumHandler$4(EndpointUtilities.java:97)
	at com.khartec.waltz.web.endpoints.EndpointUtilities$$Lambda$158/1606272155.handle(Unknown Source)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
```

**Comment by davidwatkins73** [comment]
2 problems identified:
  - root of tree points to itself (`n.id == n.parent_id`)
  - some parent_ids are invalid  (`nodesById.get(n.parent_id) == null`)

**Comment by davidwatkins73** [comment]
**MariaDB**

```
# Show Problem rows
SELECT * 
FROM organisational_unit 
WHERE parent_id = id;

SELECT *
FROM organisational_unit c
WHERE NOT EXISTS(SELECT id FROM organisational_unit p WHERE p.id = c.parent_id);


# Fix problem rows
UPDATE organisational_unit
SET parent_id = NULL
WHERE parent_id = id;

UPDATE organisational_unit
SET parent_id = NULL
WHERE id IN (
    SELECT id FROM (
      SELECT c.id
      FROM organisational_unit c
      WHERE NOT EXISTS(SELECT id FROM organisational_unit p WHERE p.id = c.parent_id)) AS t);

```

**Comment by davidwatkins73** [comment]
**MSSQL**

```
-- Show Problem rows
SELECT *
FROM organisational_unit
WHERE parent_id = id;

SELECT *
FROM organisational_unit c
WHERE NOT EXISTS(SELECT id FROM organisational_unit p WHERE p.id = c.parent_id);


-- Fix problem rows
UPDATE organisational_unit
SET parent_id = NULL
WHERE parent_id = id;

UPDATE organisational_unit
SET parent_id = NULL
WHERE id IN (
   SELECT c.id
   FROM organisational_unit c
   WHERE NOT EXISTS(SELECT id FROM organisational_unit p WHERE p.id = c.parent_id));
```

**Comment by davidwatkins73** [comment]
Partially fixed.  Now protects against case 1 (parent pointing to itself).  Case 2 (invalid parents) should be cleaned at source.  However a utility should be created to highlight inconsistencies in the data to aid problem diagnosis - another issue will be created for this purpose.
