### ISSUE TITLE
Fulltext search bug

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#589]
```
11:21:22.815 [http-nio-12792-exec-7] ERROR com.khartec.waltz.web.Main - Exception: SQL [select 
  [organisational_unit].[id], 
  [organisational_unit].[name], 
  [organisational_unit].[description], 
  [organisational_unit].[kind], 
  [organisational_unit].[parent_id], 
  [organisational_unit].[created_at], 
  [organisational_unit].[updated_at]
from [organisational_unit]
where (CONTAINS(*, '3d AND [pr'))
order by (select 0)
offset 0 rows fetch next ? rows only]; Syntax error near '[' in the full-text search condition '3d AND [pr'. / org.jooq.exception.DataAccessException
org.jooq.exception.DataAccessException: SQL [select 
  [organisational_unit].[id], 
  [organisational_unit].[name], 
  [organisational_unit].[description], 
  [organisational_unit].[kind], 
  [organisational_unit].[parent_id], 
  [organisational_unit].[created_at], 
  [organisational_unit].[updated_at]
from [organisational_unit]
where (CONTAINS(*, '3d AND [pr'))
order by (select 0)
offset 0 rows fetch next ? rows only]; Syntax error near '[' in the full-text search condition '3d AND [pr'.
	at org.jooq.impl.Tools.translate(Tools.java:1690)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:659)
```

**Comment by davidwatkins73** [comment]
and...

```
from [change_initiative]
where (CONTAINS(*, 'Structured AND Data AND Managem,'))
order by (select 0)
offset 0 rows fetch next ? rows only]; Syntax error near ',' in the full-text search condition 'Structured AND Data AND Managem,'.
	at org.jooq.impl.Tools.translate(Tools.java:1690)
```

**Comment by davidwatkins73** [comment]
Bad chars:
```
[ ] ' | "!%(),~
```
