### ISSUE TITLE
Exception thrown by attempting to add duplicate flows

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#592]
```

)]; Violation of UNIQUE KEY constraint 'unique_data_flow'. Cannot insert duplicate key in object 'dbo.data_flow'. The duplicate key value is (APPLICATION, 16024, APPLICATION, 17768).
	at org.jooq.impl.Tools.translate(Tools.java:1690)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:659)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:177)
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:143)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:139)
	at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:185)
	at org.jooq.impl.UpdatableRecordImpl.access$000(UpdatableRecordImpl.java:85)
	at org.jooq.impl.UpdatableRecordImpl$1.operate(UpdatableRecordImpl.java:135)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:131)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:123)
	at com.khartec.waltz.data.data_flow.DataFlowDao.addFlow(DataFlowDao.java:127)
	at com.khartec.waltz.service.data_flow.DataFlowService.addFlow(DataFlowService.java:121)
	at com.khartec.waltz.web.endpoints.api.DataFlowsEndpoint.addFlowRoute(DataFlowsEndpoint.java:111)
	at com.khartec.waltz.web.endpoints.EndpointUtilities.lambda$wrapDatumHandler$4(EndpointUtilities.java:95)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
```

**Comment by kamransaleem** [comment]
Happens when the user clicks apply twice or when two users are attempting to insert the same dataflow.

{"message":"Exception: SQL [insert into [data_flow] (\n  [source_entity_kind], \n  [source_entity_id], \n  [target_entity_kind], \n  [target_entity_id], \n  [provenance]\n)\nvalues (\n  ?, \n  ?, \n  ?, \n  ?, \n  ?\n)]; Violation of UNIQUE KEY constraint 'unique_data_flow'. Cannot insert duplicate key in object 'dbo.data_flow'. The duplicate key value is (APPLICATION, 19711, APPLICATION, 20506). / org.jooq.exception.DataAccessException","id":"unknown"}


Suggested fix:
- Disable the Apply button on first click whilst the save is happening
- If there is a race condition between more than one user, report the error as a notification and ask the user to refresh his page because the flows have been updated or refresh automatically?
