### ISSUE TITLE
Command line build crashes javac on Mac OSX

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#93]
Build crashes with a message similar to:

```
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building waltz-model 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ waltz-model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/xxx/Development/Waltz/waltz/waltz-model/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ waltz-model ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 129 source files to /Users/xxx/Development/Waltz/waltz/waltz-model/target/classes
An exception has occurred in the compiler (1.8.0_74). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.IllegalStateException: endPosTable already set
	at com.sun.tools.javac.util.DiagnosticSource.setEndPosTable(DiagnosticSource.java:136)
	at com.sun.tools.javac.util.Log.setEndPosTable(Log.java:350)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:667)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:950)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:892)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:921)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1187)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
...
````

**Comment by davidwatkins73** [comment]
This is caused by a problem with javac's incremental compiler.  It can be worked around using:

``` mvn clean compile ```

which forces a complete rebuild.

Alternatively the maven build can be instructed to disable the incremental compiler.  This is the approach we will adopt to resolve this issue.

**Comment by davidwatkins73** [comment]
Closing


---

@mcneilm - resolving crashing compilation.
